BEGIN TRANSACTION;

-- ============================================================
-- HISTORIALES - DEXCOM
-- ============================================================
-- Fast Line = 1, TSA = 2, DSD05 = 3

-- Fast Line (88 codigos)
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 LIF', 'AX1 Falla por elevador', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 CON', 'AX1 Falla por conveyor', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 BF SP', 'AX1 Falla por Bowl Feeder (Stripper Plate)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 IF SP', 'AX1 Falla por Inline Feeder (Stripper Plate)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 BF S', 'AX1 Falla por Bowl Feeder (Spring/Resorte)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 PAC', 'AX1 Pallets Atorados en conveyors (piezas atoradas)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 BCODE', 'AX1 Falla en lectura de Pallet  Bar Code (codigo de barras)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 CLRBPICK', 'AX1 Colision Robot Pick (recoleccion de pieza en nido SP)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 RBT SP', 'AX1 Ensamble de SP (Robot Stripper Plate)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 RBT S', 'AX1 Ensamble de SP(Robot Spring)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 L&L', 'AX1 Ensamble de SP (Lift Located)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 EOAT', 'AX1 Ensamble de SP (Tooling)  Herramienta del robot', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 SREOAT', 'AX1 Ensamble de SP (Sensor Robot) Herramienta del robot', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 CAL', 'AX1 Ensamble de SP (Calibracion Robot)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 SS', 'AX1 Falla en Sensor Spring', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 PAL', 'AX1 Falla en Sensor Pallet', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 PZ', 'AX1 Falla en Sensor Pieza', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 SLD', 'AX1 Falla en Slider', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 SV', 'AX1 Falla en sistema de Vision', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 SEG', 'AX1 Falla en guarda de seguridad', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 SEG', 'AX1 Suministro Electrico', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX1 PAB', 'AX1 Presion Aire Baja', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 CON', 'AX2 Falla por conveyor', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 BF NC', 'AX2 Falla por Bowl Feeder (Needle Carriage)', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 IF NC', 'AX2 Falla por Inline Feeder (Needle Carriage)', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 PAC', 'AX2 Pallets Atorados en conveyors (piezas atoradas)', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 BCODE', 'AX2 Falla en lectura de Pallet  Bar Code (codigo de barras)', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 RP', 'AX2 Colision Robot Pick (recoleccion de pieza en nido)', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 RBT NC', 'AX2 Ensamble de NC (Robot Needle Carriage)', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 MAT NC', 'AX2 Ensamble de NC (Material)', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 L&L', 'AX2 Ensamble de NC (Lift Located)', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 EOAT', 'AX2 Ensamble de NC (Tooling)  Herramienta del robot', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 SR', 'AX2 Ensamble de NC (Sensor Robot) Herramienta del robot', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 CAL', 'AX2 Ensamble de NC (Calibracion Robot)', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 SS', 'AX2 Falla en Sensor Spring', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 PAL', 'AX2 Falla en Sensor Pallet', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 PZ', 'AX2 Falla en Sensor Pieza', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 SLD', 'AX2 Falla en Slider', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 SV', 'AX2 Falla en sistema de Vision', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 SEG', 'AX2 Falla en guarda de seguridad', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 RFT', 'AX2 Falla prueba RFT', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 SEG', 'AX2 Suministro Electrico', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX2 PAB', 'AX2 Presion Aire Baja', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 CON', 'AX3 Falla por conveyor', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 BF IH', 'AX3 Falla por Bowl Feeder (Inner Housing)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 IF IH', 'AX3 Falla por Inline Feeder (Inner Housing)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 BF S', 'AX3 Falla por Carga de Resorte (Resorte/Spring)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 PAC', 'AX3 Pallets Atorados en conveyors (piezas atoradas)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 BCODE', 'AX3 Falla en lectura de Pallet  Bar Code (codigo de barras)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 RP IH', 'AX3 Colision Robot Pick (Inner Housing)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 RBT IH', 'AX3 Ensamble de IH (Robot Inner Housing)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 RBT S', 'AX3 Ensamble de IH (Spring)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 CAL', 'AX3 Ensamble de IH (Calibracion Robot)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 L&L', 'AX3 Ensamble de IH (Lift Located)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 EOAT', 'AX3 Ensamble de IH (Tooling)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 SR', 'AX3 Ensamble de IH (Sensor Robot)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 SS', 'AX3 Falla en Sensor Spring', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 PAL', 'AX3 Falla en Sensor Pallet', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 PZ', 'AX3 Falla en Sensor Pieza', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 SLD', 'AX3 Falla en Slider', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 SV', 'AX3 Falla en sistema de Vision', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 SEG', 'AX3 Falla en guarda de seguridad', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 SV', 'AX3 Sistema de Vision', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 SEG', 'AX3 Suministro electrico', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX3 PAB', 'AX3 Presion Aire Baja', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX4 CON', 'AX4 Falla de Conveyor', 'AX4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX4 RBT', 'AX4 Falla de Robot', 'AX4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX4 SV', 'AX4 Sistema de vision (Scrap)', 'AX4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX4 PAC', 'AX4 Pallets Atorados en conveyors (piezas atoradas)', 'AX4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX4 BCODE', 'AX4 Falla en lectura de Pallet  Bar Code (codigo de barras)', 'AX4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX4 EC', 'AX4 Elevador de Charolas', 'AX4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX4 LIF', 'AX4 Falla Elevador de salida', 'AX4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX4 SE', 'AX4 Suministro Electrico', 'AX4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FL AX4 PAB', 'AX4 Presion Aire Baja', 'AX4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'SUT UP', 'Toma de parametros', 'Generales');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FSER', 'Falla en servidor', 'Generales');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'GFSE', 'Falta del Suministro Electrico', 'Generales');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'GFAC', 'Falta del Aire comprimido', 'Generales');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'RAMUP', 'Personal en entrenamiento', 'Generales');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'QCSAMPLES', 'Pruebas de Calidad', 'Generales');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'QCCAL', 'Calibracion', 'Generales');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'FMAT', 'Falta de material', 'Generales');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'MATTO PREV', 'Mantenimiento Preventivo', 'Generales');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'PERIFERICO', 'Perifericos', 'Generales');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'PLAN-PROD', 'Acomodo / distribucion de Personal', 'Generales');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'MAT REP', 'Problemas con materiales (cambios)', 'Generales');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'ENGTEST', 'Pruebas de Ingenieria', 'Generales');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (1, 'COMM', 'Juntas Comunicacion', 'Generales');

-- TSA (73 codigos)
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX1 LIF', 'AX1 Falla por elevador', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX1 CON', 'AX1 Falla por conveyor', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX1 ATM', 'AX1 Atoramiento en transferencia de magneto', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX1 EM', 'AX1 Ensamble de magneto', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX1 CMAG', 'AX1 Falla en carga de magneto (Invertido)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX1 BF SP', 'AX1 Falla por Bowl Feeder (Stripper Plate)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX1 IF SP', 'AX1 Falla por Inline Feeder (Stripper Plate)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX1 PAC', 'AX1 Pallets Atorados en conveyors (piezas atoradas)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX1 RBLD30', 'AX1 Falla en Robot Carga (recoleccion de pieza de SP St 30)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX1 RBULD40', 'AX1 Falla en Robot Descarga (recoleccion de pieza de SP St 40)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX1 L&L', 'AX1 Ensamble de SP (Lift Located)', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX1 PAB', 'AX1 Presion Aire Baja', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX1 SE', 'AX1 Suministro Electrico', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX1 AMAT', 'AX1 Atoramiento bin de material', 'AX1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 CON', 'AX2 Falla por conveyor', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 BF NC', 'AX2 Falla por Bowl Feeder (Needle Carriage)', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 IF NC', 'AX2 Falla por Inline Feeder (Needle Carriage)', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 PAC', 'AX2 Pallets Atorados (Conveyor)', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 RBT', 'AX2 Ensamble de NC (Robot)', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 RBT MAT', 'AX2 Ensamble de NC (Material) Orientacion', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 RBT RP', 'AX2 Colision Robot Pick (recoleccion de pieza en nido)', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 RBT L&L', 'AX2 Ensamble de NC (Lift Located)', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 RBT EOAT', 'AX2 Ensamble de NC (Tooling)  Herramienta del robot', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 RBT SR', 'AX2 Ensamble de NC (Sensor Robot) Herramienta del robot', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 RBT CAL', 'AX2 Ensamble de NC (Calibracion Robot)', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 SS', 'AX2 Falla en Sensor Spring', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 PAL', 'AX2 Falla en Sensor Pallet', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 PZ', 'AX2 Falla en Sensor Pieza', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 SLD', 'AX2 Falla en Sliders', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 SEG', 'AX2 Falla en guarda de seguridad', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 RFT', 'AX2 Falla prueba RFT', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 SE', 'AX2 Suministro Electrico', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX2 PAB', 'AX2 Presion Aire Baja', 'AX2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 LIF', 'AX3 Falla Elevador', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 CON', 'AX3 Falla por conveyor', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 BF IH', 'AX3 Falla por Bowl Feeder (Inner Housing)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 IF IH', 'AX3 Falla por Inline Feeder (Inner Housing)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 PAC', 'AX3 Pallets atorados (Conveyor)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 RBT', 'AX3 Ensamble de IH (Robot)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 RBT MAT', 'AX3 Ensamble de IH (Material)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 RBT RP', 'AX3 Colision Robot Pick', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 RBT L&L', 'AX3 Ensamble de IH (Lift Located)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 RBT EOAT', 'AX3 Ensamble de IH (Tooling)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 RBT SR', 'AX3 Ensamble de IH (Sensor Robot)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 RBT CAL', 'AX3 Ensamble de IH (Calibracion Robot)', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 SS', 'AX3 Falla en Sensor Spring', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 PAL', 'AX3 Falla en Sensor Pallet', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 PZ', 'AX3 Falla en Sensor Pieza', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 SLD', 'AX3 Falla en Sliders', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 SEG', 'AX3 Falla en guarda de seguridad', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 UD', 'AX3 Servo de Descarga', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 SV', 'AX3 Sistema de Vision', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 SE', 'AX3 Suministro electrico', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'AX3 PAB', 'AX3 Presion Baja', 'AX3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'BIC CON', 'BIC Falla de Conveyor', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'BIC RBT', 'BIC Falla de Robot', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'BIC SV', 'BIC Sistema de vision (Scrap)', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'BIC ACMAT', 'BIC Conveyor detenido acumulamiento de material', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'BIC LIF', 'BIC Elevador de Charolas', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'SUT UP', 'Toma de parametros', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'GFSE', 'Falta del Suministro Electrico', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'GFAC', 'Falta del Aire comprimido', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'RAMUP', 'Personal en entrenamiento', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'QCSAMPLES', 'Pruebas de Calidad', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'QCCAL', 'Calibracion', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'LIMPMAQ', 'Limpieza de maquina (retiro de scrap, FIFO reset)', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'FMAT', 'Falta de material', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'MATTO PREV', 'Mantenimiento Preventivo', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'PERIFERICO', 'Perifericos', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'PLAN-PROD', 'Acomodo / distribucion de Personal', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'MAT REP', 'Problemas con materiales (cambios)', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'ENGTEST', 'Pruebas de Ingenieria', 'BIC');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (2, 'COMM', 'Juntas Comunicacion', 'BIC');

-- DSD05 (86 codigos)
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M1 St01', 'Cell 1 Check Empty Pallet St01', 'Modulo 1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M1 St02', 'St02 Falla por transferencia de Canula Hub', 'Modulo 1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M1 St03', 'Cell 1  Check Cannula Hubs St03', 'Modulo 1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M1 St04', 'St04 Falla por Transferencia de Inner Hub', 'Modulo 1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M1 St05', 'Cell 1 Check Inner Hub  St05', 'Modulo 1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M 1 St06', 'St07 Falla por Transferencia de Outher Hub', 'Modulo 1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M1 St07', 'Cell 1 Check Outer Hub St08', 'Modulo 1');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M2 St04', 'St04 Falla por transferencia de canula', 'Modulo 2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M2 St05', 'Cell 2 Set Cannula St05', 'Modulo 2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M2 St06', 'Cell 2 Check Cannula St06', 'Modulo 2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M2 St07', 'St04 Fallapor  transferencia de Aguja', 'Modulo 2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M2 St08', 'St08 Fallas Altura de Aguja', 'Modulo 2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M2 St09', 'St09 Fallas por dispensado Dymax', 'Modulo 2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M2 St10', 'Cell 2 UV Cure St10', 'Modulo 2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M2 St11', 'Cell 2 UV Cure  St11', 'Modulo 2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M2 St12', 'Cell 2 UV Cure  St12', 'Modulo 2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M2 St13', 'St13 Fallas por Push Test', 'Modulo 2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M2 St14', 'St08 Fallas por dispensado Dymax', 'Modulo 2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M2 St15', 'Cell 2 Vision Check Needle Tip St15', 'Modulo 2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M2 St16', 'St08 Fallas por cargado de Booster', 'Modulo 2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M2 St17', 'Cell 3 Offload Inner Hub St17', 'Modulo 2');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M3 St02', 'St02 Fallas por ensamble de Inner Hub', 'Modulo 3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M3 St03', 'Cell 3 Check Inner Hub St03', 'Modulo 3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M3 St04', 'Cell 3 Check Presence St04', 'Modulo 3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M3 St05', 'Cell 3 Offload Outer Hub  St05', 'Modulo 3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M3 St06', 'Cell 3 Check Outer Hub St06', 'Modulo 3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M3 St07', 'Cell 3 Transfer S/A St07', 'Modulo 3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M3 St08', 'St08 Fallas por Ensamble Canula / Aguja', 'Modulo 3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M3 St09', 'St09 Falla por deteccion por male ensamble', 'Modulo 3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M3 St10', 'St08 Fallas por PolyFeed', 'Modulo 3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M3 St11', 'Cell 3 Press Puck  St11', 'Modulo 3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M3 St12', 'Cell 3 Check Pallet Position  St12', 'Modulo 3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M3 St13', 'Cell 3 Vision Check Puck   St13', 'Modulo 3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M3 St15', 'Cell 3 Transfer Hub S/A  St15', 'Modulo 3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M3 St16', 'Cell 3  Check Hub S/A St16', 'Modulo 3');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M4 St02', 'St02 Fallas por CheckOcclusion', 'Modulo 4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M4 St05', 'St05 Fallas por CheckOcclusion', 'Modulo 4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M4 St07', 'St07 Falla por Dispensado de PJ', 'Modulo 4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M4 St08', 'St08 Falla por Dispensado de PJ', 'Modulo 4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M4 St09', 'St09 Falla por Sistema de Vision', 'Modulo 4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M4 St10', 'St10 Falla por Sistema de Vision', 'Modulo 4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M4 St11', 'St11 Falla por Transferencia de Archer', 'Modulo 4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M4 St12', 'St12 Falla por Transferencia de Archer', 'Modulo 4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M4 St13', 'St13 Falla por Transferencia de Scrap', 'Modulo 4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M4 St14', 'St14 Falla por Transferencia de Scrap', 'Modulo 4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M4 St15', 'St15 Falla por Transferencia de Archer', 'Modulo 4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M4 St16', 'St16 Falla por Transferencia de Archer', 'Modulo 4');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M5 St01', 'Cell 5 Check DH and CB St1', 'Modulo 5');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M5 St02', 'St02 Falla por Transferencia de Archer', 'Modulo 5');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M5 St03', 'Cell 5 Check hub S/A St3', 'Modulo 5');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M5 St04', 'Cell 5 Press Hub S/A St4', 'Modulo 5');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M5 St05', 'St05 Falla por Sistema de Vision', 'Modulo 5');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M5 St06', 'Cell 5 Check Keel Height St6', 'Modulo 5');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M5 St07', 'St07 Falla por Transferencia de Scrap', 'Modulo 5');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M5 St08', 'St08 Falla por Transferencia de Scrap', 'Modulo 5');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M6 St01', 'Cell 6 Check Empty St1', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M6 St02', 'Cell 6 Check Empty St2', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M6 St03', 'St03 Fallas por Carga de Housing', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M6 St04', 'St04 Fallas por sellado', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M6 St05', 'St05 Fallas por transferencia de Parche', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M6 St06', 'St05 Fallas por Sistema de Vision', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M6 St07', 'St05 Fallas por Sistema de Vision', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M6 St11', 'St11 Fallas por transferencia de Parche', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M6 St12', 'St12 Fallas por transferencia de Parche', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M6 St15', 'Cell 6 Check Present / QC Offload St15', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'M6 St16', 'Cell 6 Check Present / QC Offload St16', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, '1LTH', 'Load Tray Handler', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, '2UTH', 'Unload Tray Handler', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'LOCN', 'Carga de Canula', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'LOAG', 'Carga de Aguja', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'LOPJ', 'Carga de Petrolato', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'LODYX', 'Carga de Dymax', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'LOROL', 'Carga de Rollo de Parche M6 St04', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'DHR', 'Despeje de linea', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'QCSELL', 'Pruebas de Sellado', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'QCPNG', 'Pruebas de Pin Gauge', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'GFSE', 'Falta del suministro electrico', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'GFAC', 'Falta de Aire Comprimido', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'MATTO PREV', 'Mantenimiento Preventivo', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'PERIFERICO', 'Perifericos', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'PLAN-PROD', 'Acomodo / distribucion de Personal', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'ENGTEST', 'Pruebas de Ingenieria', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'COMM', 'Juntas / Comunicacion', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'QCCAL', 'Calibraciones', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'MAT REP', 'Problemas con materiales (cambios)', 'Modulo 6');
INSERT OR IGNORE INTO codigos_historial (linea_id, codigo, descripcion, modulo) VALUES (3, 'FMAT', 'Falta de Material', 'Modulo 6');

COMMIT;
